name: Res_cifar100_imb001_ETF_DR
print_freq: 40
workers: 4
log_dir: 'logs'
model_dir: 'ckps'

# dataset & model setting
dataset: 'cifar100'
data_path:  './data_cifar/' #'./data/cifar/cifar-10-batches-py/'
num_classes: 100
imb_factor: 0.01
backbone: 'resnet32_fe_c100'
resume: ''
head_class_idx:
  - 0
  - 36
med_class_idx:
  - 36
  - 71
tail_class_idx:
  - 71
  - 100


# distributed training
deterministic: False
distributed: False
gpu: 0
world_size: -1
rank: -1
dist_url: 'tcp://224.66.41.62:23456'
dist_backend: 'nccl'
multiprocessing_distributed: False



# Train
mode: 'stage1'
lr: 0.1
batch_size: 128
weight_decay: 2e-4
num_epochs: 200
momentum: 0.9
cos: False
mixup: True
alpha: 1.0



ETF_classifier: True
reg_dot_loss: True
